export const deckActors = [
  {value: 'Michael Cera'},
  {value: 'Emma Stone'},
  {value: 'Jennifer Lawrence'},
  {value: 'Anna Kendrick'},
  {value: 'Amanda Seyfried'},
  {value: 'James McAvoy'},
  {value: 'Benedict Cumberbatch'},
  {value: 'Christian Bale'},
  {value: 'Brad Pitt'},
  {value: 'Robert de Niro'},
  {value: 'Jack Nicholson'},
  {value: 'Tom Hanks'},
  {value: 'Marlon Brando'},
  {value: 'Leonardo DiCaprio'},
  {value: 'Johnny Depp'},
  {value: 'Al Pacino'},
  {value: 'Denzel Washington'},
  {value: 'Daniel Day-Lewis'},
  {value: 'Tom Cruise'},
  {value: 'Dustin Hoffman'},
  {value: 'Sean Penn'},
  {value: 'Harrison Ford'},
  {value: 'George Clooney'},
  {value: 'Anthony Hopkins'},
  {value: 'Russel Crowe'},
  {value: 'Katharine Hepburn'},
  {value: 'Meryl Streep'},
  {value: 'Anne Hathaway'},
  {value: 'Marilyn Monroe'},
  {value: 'Kate Winslet'},
  {value: 'Cate Blanchet'},
  {value: 'Helen Mirren'},
  {value: 'Nicole Kidman'},
  {value: 'Natalie Portman'},
  {value: 'Jodie Foster'},
  {value: 'Amy Adams'},
  {value: 'Julia Roberts'},
  {value: 'Emma Thompson'},
  {value: 'Charlize Theron'},
  {value: 'Matt Damon'},
  {value: 'Christoph Waltz'},
  {value: 'Sean Connery'},
  {value: 'Kevin Spacey'},
  {value: 'Liam Neeson'},
  {value: 'Edward Norton'}
]

export const deckMovies = [
  {value: 'Dunkirk'},
  {value: 'Scott Pilgrim vs The World'},
  {value: 'Superbad'},
  {value: 'Inception'},
  {value: 'Memento'},
  {value: 'The Prestige'},
  {value: 'Reservoir Dogs'},
  {value: 'Up!'},
  {value: 'Rocky'},
  {value: 'Memento'},
  {value: 'Braveheart'},
  {value: 'Slumdog Millionaire'},
  {value: 'Seven'},
  {value: 'Wall-E'},
  {value: 'Ghostbusters'},
  {value: 'Brokeback Mountain'},
  {value: 'Gladiator'},
  {value: 'Avatar'},
  {value: 'Amelie'},
  {value: 'The Dark Knight'},
  {value: 'The Big Lebowski'},
  {value: 'Jurassic Park'},
  {value: 'Alien vs Predator'},
  {value: 'Saving Private Ryan'},
  {value: 'Titanic'},
  {value: 'The Matrix'},
  {value: 'Toy Story'},
  {value: 'Fight Club'},
  {value: 'American Beauty'},
  {value: 'Star Wars'},
  {value: 'Harry Potter'},
  {value: 'The Breakfast Club'},
  {value: 'Deadpool'},
  {value: 'The Silence of the Lambs'},
  {value: 'Goodfellas'},
  {value: 'Django Unchained'},
  {value: 'Kill Bill'},
  {value: 'Pulp Fiction'},
  {value: 'Gone With The Wind'},
  {value: 'Forrest Gump'},
  {value: 'The Godfather'},
  {value: 'Casablanca'},
  {value: 'The Shawshank Redemption'}
]

export const deckTVShows = [
  {value: 'Community'},
  {value: 'Brooklyn Nine-Nine'},
  {value: '13 Reasons Why'},
  {value: 'Game of Thrones'}
]

export const deckMusic = [
  {value: '50 Cent'},
  {value: 'Christina Aguilera'},
  {value: 'Adele'},
  {value: 'The Weeknd'},
  {value: 'Michael Jackson'},
  {value: 'Justin Bieber'},
  {value: 'Justin Timberlake'},
  {value: 'Lana Del Rey'},
  {value: 'Lil Wayne'},
  {value: 'Taylor Swift'},
  {value: 'Ariana Grande'},
  {value: 'Pharrel Williams'},
  {value: 'Daft Punk'},
  {value: 'Macklemore'},
  {value: 'Selena Gomez'},
  {value: 'Frank Sinatra'},
  {value: 'Iggy Azalea'},
  {value: 'Ellie Goulding'},
  {value: 'Gwen Stefani'},
  {value: 'Kanye West'},
  {value: 'Elvis Presley'},
  {value: 'John Lenon'},
  {value: 'Lady Gaga'},
  {value: 'Britney Spears'},
  {value: 'Skrillex'},
  {value: 'Rihanna'},
  {value: 'David Bowie'},
  {value: 'Akon'},
  {value: 'Bob Marley'},
  {value: 'Freddy Mercury'},
  {value: 'Miley Cyrus'},
  {value: 'Adam Levine'},
  {value: 'Bob Dylan'},
  {value: 'Katy Perry'},
  {value: 'Jimi Hendrix'},
  {value: 'Paul McCartney'},
  {value: 'Jennifer Lopez'}
]

export const deckArtists = [
  {value: ''},
]

export const deckSports = [
  {value: 'Andre Agassi'},
  {value: 'Roger Federer'},
]
